#!/bin/sh -e

## hyphop ##

## one-line command - easy make 

REP=miZy-builder

usage() { echo "USAGE:

    wget https://raw.githubusercontent.com/hyphop/$REP/master/make_it_easy -O- | sh -

"
}

[ -p /tmp/zero_builder ] || mkdir -p /tmp/zero_builder 
cd /tmp/zero_builder || exit 1

git clone https://github.com/hyphop/$REP.git
cd $REP || exit 1

./miZy_builder_vm_generate yes




