#!/bin/sh

## hyphop ##

dir=scripts ./tools/http --daemon

. ./miZy_builder_vm.net.conf

#echo "http script"
#./miZy_builder_vm start run=http://$ip0h/init.hello.script

echo "tar script"
./miZy_builder_vm start run=scripts/init.hello.script disk=miZyBldr.ovl
