#!/bin/bash

D=$(dirname $0)

cp $D/.files /tmp/.files || {
    echo "[e] plz check $D/.files" 1>&2
    exit 1
}

for FILE in "$@"; do
#

NAME=${FILE/*\/}

echo "[i] update $NAME => $FILE" 1>&2


done